version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: shop-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storeplate-db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./shop-be
    container_name: shop-backend
    restart: always
    env_file:
      - ./shop-be/.env
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  frontend:
    build: ./shop-fe
    container_name: shop-frontend
    restart: always
    env_file:
      - ./shop-fe/.env.production
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql_data:
